# 本地测试配置文件，使用时更改名称为 config_pro.yaml
# go run main.go
# HTTP Server.
server:
  address: ":8018"
  serverName: "garden-be"
  mode: "debug"

# Database.
mysql:
  username: "root"
  password: "123456"
  # if run in container using 'container name or ip'
  dbHost: "mysql"
  dbPort: 3306
  dbName: "app_db"

# Log.
log:
  logFileDir: "./tmp"
  appName: "garden-be"
  maxSize: 512
  maxBackups: 64
  maxAge: 7

# nsq.
nsq:
  nsq_producer_host: "10.4.7.71"
  nsq_producer_port: 4150 # tcp
  nsq_subscribe_host: "10.4.7.71"
  nsq_subscribe_port: 4150 # tcp

# jwt
jwt:
  secret: "secret"

# userPassword
userPassword:
  salt: "salt"
  